TypeError: no implicit conversion of nil into String (#1738)
* When view-component is required in a Rails::Engine the variable
`ViewComponent::Base.config.view_component_path` is null
and `Regexp.quote(ViewComponent::Base.config.view_component_path)`
raises `TypeError: no implicit conversion of nil into String`.

Checking `defined?(Rails) && Rails.application` seems to solve
the problem.

* changelog

---------

Co-authored-by: Joel Hawksley <joel@hawksley.org>