Write test to validate slots with non-keyword argument
Before the fix, this test fail with
ArgumentError: wrong number of arguments
due tu double splat operator that transform
**{} in {} which is then past as a standard argument