add failing test
test returns

```
CapybaraDslTest#test_assert_link:
ArgumentError: Unused parameters passed to Capybara::Queries::SelectorQuery : [:link, "My link"]
```