Fix bug where previews didn't work when monkey patch was disabled.
On Rails < 6.1 when render monkey patch is disabled by setting
view_component.render_monkey_patch_enabled = false and changing
render for render_component inside previews, an error of type
NoMethodError: undefined method `render_component' for Preview
is raised.

This PR adds a test to validate the error and adds the missing
render_component method to ViewComponent::Preview. Previews
keep working as usual regardless the render_monkey_patch value